glu-lang/glu

CMakeLists.txt, include/GIL/BasicBlock.hpp, include/GIL/InstBase.hpp, lib/GIL/BasicBlock.cpp, lib/GIL/CMakeLists.txt, lib/GIL/InstBase.cpp, tools/gluc/sources/main.cpp
=> Feature: add basic block

include/GIL/BasicBlock.hpp, include/GIL/InstBase.hpp, include/GIL/InstKind.def, include/GIL/InstVisitor.hpp, lib/GIL/BasicBlock.cpp, lib/GIL/InstBase.cpp
=> Add TerminatorInst

include/GIL/InstBase.hpp
=> Inst literal

include/AST/Types/BoolTy.hpp, include/AST/Types/CharTy.hpp, include/AST/Types/Types.hpp
=> Feature: add `CharTy` and `BoolTy` class in AST

include/AST/Types/FunctionTy.hpp, include/AST/Types/Types.hpp
=> Feature: add `FunctionTy` class in AST

include/AST/ASTNode.hpp
=> feat: create stmtbase and declbase

include/GIL/BasicBlock.hpp, include/GIL/Function.hpp, include/GIL/InstBase.hpp, lib/GIL/BasicBlock.cpp, lib/GIL/CMakeLists.txt, lib/GIL/Function.cpp
=> Feature: add `gil::Function` class

include/GIL/BasicBlock.hpp
=> Add parameters to BasicBlock

include/AST/Types/EnumTy.hpp, include/AST/Types/StructTy.hpp, include/AST/Types/Types.hpp, lib/GIL/CMakeLists.txt
=> feat(AST/Types): add EnumTy class

include/GIL/Type.hpp, lib/GIL/CMakeLists.txt
=> add Type class in Gil

include/AST/Types/TypeAliasTy.hpp, include/AST/Types/Types.hpp
=> feat: add TypeAliasTy

include/GIL/Instructions.hpp, include/GIL/Instructions/CallInst.hpp, lib/GIL/CMakeLists.txt, lib/GIL/CallInst.cpp
=> Feature: Call Instruction

include/GIL/BasicBlock.hpp, include/GIL/Function.hpp, include/GIL/GIL.hpp, include/GIL/GILPrinter.hpp, include/GIL/InstVisitor.hpp, include/GIL/Instructions.hpp, include/GIL/Instructions/InstBase.hpp, lib/GIL/CMakeLists.txt, lib/GIL/CallInst.cpp, lib/GIL/GIL.cpp, lib/GIL/GILPrinter.cpp, test/CMakeLists.txt, test/GIL/GILPrinter.cpp
=> GIL Printer

include/AST/Stmt/BreakStmt.hpp, include/AST/Stmt/CompoundStmt.hpp, include/AST/Stmt/ContinueStmt.hpp, test/AST/Stmt/BreakStmt.cpp, test/AST/Stmt/CompoundStmt.cpp, test/AST/Stmt/ContinueStmt.cpp, test/CMakeLists.txt
=> feat(AST): add ContinueStmt and BreakStmt

include/GIL/Instructions.hpp, include/GIL/Instructions/StructExtractInst.hpp
=> StructExtract instruction

include/GIL/Instructions.hpp, include/GIL/Instructions/CastPtrToIntInst.hpp
=> Create CastPtrToIntInst class

include/GIL/Instructions.hpp, include/GIL/Instructions/CastIntToPtrInst.hpp
=> Create CastIntToPtrInst class

include/GIL/Instructions.hpp, include/GIL/Instructions/FunctionPtrInst.hpp
=> Create FunctionPtrInst class

include/GIL/Instructions.hpp, include/GIL/Instructions/LoadInst.hpp
=> Feature: load inst

CMakeLists.txt, include/Basic/TokenKind.def, include/Basic/Tokens.hpp, include/Lexer/Lexer.hpp, include/Lexer/Scanner.hpp, lib/Lexer/CMakeLists.txt, lib/Lexer/Lexer.cpp, lib/Lexer/Scanner.l, test/CMakeLists.txt, test/Scanner/Scanner.cpp
=> [Lexer] Feat: Add FLEX scanner

include/AST/ASTContext.hpp, include/AST/ASTMemoryArena.hpp, include/Basic/MemoryArena.hpp, include/MemoryArena.hpp, test/AST/ASTContext.cpp, test/CMakeLists.txt
=> [Parser] Feature: Add memory arena

include/GIL/Instructions.hpp, include/GIL/Instructions/ConversionInst.hpp, include/GIL/Instructions/FloatExtInst.hpp, include/GIL/Instructions/IntTruncInst.hpp
=> Create FloatExtInst class

beta_test_plan.md
=> chore: add beta test plan

include/AST/Decl/EnumDecl.hpp, include/AST/Decl/StructDecl.hpp, include/AST/Decl/TypeAliasDecl.hpp, include/AST/Decls.hpp, include/AST/Types/EnumTy.hpp, include/AST/Types/StructTy.hpp
Close #53
Close #54 
Close #55
=> [AST] StructDecl & EnumDecl & TypeAliasDecl

include/AST/Expr/LiteralExpr.hpp, include/AST/Exprs.hpp
=> Feature: add LiteralExpr class and Exprs.hpp

include/AST/Expr/RefExpr.hpp, include/AST/Exprs.hpp
=> Feature: add RefExpr

include/AST/Decl/ImportDecl.hpp, include/AST/Expr/CallExpr.hpp, include/AST/Exprs.hpp, include/AST/Types/EnumTy.hpp, include/AST/Types/StructTy.hpp, test/AST/Stmt/ExpressionStmt.cpp
=> Feature: CallExpr

include/AST/Decl/ForBindingDecl.hpp, include/AST/Decl/VarLetDecl.hpp, include/AST/NodeKind.def, include/AST/Stmt/ForStmt.hpp, include/AST/Stmts.hpp
=> Create forStmt class

include/AST/Stmt/IfStmt.hpp, lib/Parser/Parser.yy, test/AST/ASTWalker.cpp
=> [Parser] Feature: Generate If & While & For Statements ASTNode in parser

include/AST/Decl/StructDecl.hpp, include/AST/Types/StructTy.hpp, lib/Parser/Parser.yy
=> [Parser] Feature: Generate `StructDecl` ASTNode and create `PointerTy` ASTNode

include/AST/Types/EnumTy.hpp, lib/Parser/Parser.yy
=> [Parser] Feature: add EnumDecl generation with this cases

include/GIL/Instructions.hpp, include/GIL/Instructions/AllocaInst.hpp, include/GIL/Instructions/InstBase.hpp, include/GIL/Type.hpp
=> AllocaInst class

include/Basic/SourceLocation.hpp, lib/AST/HashType.cpp, test/AST/ASTContext.cpp
=> [Bug] Fix: Add constistance in Hash and Equal visitors

include/AST/ASTNode.hpp, include/AST/Expr/LiteralExpr.hpp
=>  Feature: add `TypeBase *` in all Exprs in AST

include/GIL/InstKind.def, include/GIL/Instructions/AggregateInst.hpp, include/GIL/Instructions/StructExtractInst.hpp
=> Feature: add AggregateInst class

include/GIL/InstKind.def, include/GIL/Instructions.hpp, include/GIL/Instructions/PtrOffsetInst.hpp
=> feat: basic form of ptrOffsetInst

include/AST/ASTVisitor.hpp, include/AST/ASTWalker.hpp, lib/ASTPrinter/ASTPrinter.cpp, lib/GILGen/GILGenExpr.hpp, lib/GILGen/GILGenLValue.hpp, test/AST/ASTWalker.cpp
=> Refactor: Support having both pre- and post- actions in the same ASTWalker

include/Basic/Diagnostic.hpp, include/Basic/SourceManager.hpp, lib/Basic/CMakeLists.txt, lib/Basic/Diagnostic.cpp, lib/Basic/SourceManager.cpp, test/Basic/DiagnosticTest.cpp, test/CMakeLists.txt
=> Feature: Diagnostic

include/AST/ASTContext.hpp, include/AST/Decl/ModuleDecl.hpp, lib/Parser/Parser.yy, tools/gluc/sources/main.cpp
=> refactor: add ASTContext to ModuleDecl

lib/Sema/CSWalker.cpp
=>  Feature: add ExpressionStmt constraint

include/GIL/InstVisitor.hpp, include/GIL/Instructions/ReturnInst.hpp, include/GIL/Module.hpp, include/IRGen/IRGen.hpp, lib/GILGen/GILGenStmt.cpp, lib/IRGen/IRGen.cpp, lib/IRGen/TypeLowering.hpp
=> Feature: IRGen base

lib/IRGen/IRGen.cpp
=> Feature(IRGen): Generate IR for Constants

include/GIL/Instructions/CallInst.hpp, include/GILGen/Context.hpp, lib/GIL/CallInst.cpp, lib/IRGen/IRGen.cpp, test/GIL/GILPrinter.cpp
=> Feature: Generate IR for CallInst

lib/Sema/CSWalker.cpp
=>  Feature: add CallExpr constraint

lib/IRGen/IRGen.cpp
=> Feature: Generate IR for Branches

include/GIL/Instructions/AllocaInst.hpp, include/GILGen/Context.hpp, lib/GILGen/GILGenExpr.hpp, lib/GILGen/GILGenLValue.hpp, lib/GILGen/GILGenStmt.cpp, lib/GILGen/Scope.hpp
=> [GILGen] Feature: Support variable declaration

include/AST/Decl/EnumDecl.hpp, include/AST/Decl/FunctionDecl.hpp, include/AST/Decl/StructDecl.hpp, include/AST/Decl/TypeAliasDecl.hpp, include/AST/Expr/CastExpr.hpp, include/Sema/TypeMapper.hpp
=> Fix: Macros in Tymapper

include/Sema/ConstraintSystem.hpp, lib/Sema/ConstraintSystem.cpp
=> Feature: apply bind

include/Sema/ConstraintSystem.hpp, lib/Sema/ConstraintSystem.cpp
=> Feature: Resolve Defaultable

include/GIL/Instructions/StructFieldPtrInst.hpp, lib/GILGen/Context.hpp, lib/GILGen/GILGenLValue.hpp
=> Feature: Implement StructMemberExpr LValue Generation

lib/Parser/Parser.yy, test/Parser/Function.cpp, test/functional/run/function_overloads.glu
=> Feature: add overloadables support in parser for operator declarations

include/GIL/Function.hpp, include/Sema/Constraint.hpp, include/Sema/ConstraintSystem.hpp, lib/GILGen/Context.hpp, lib/IRGen/IRGen.cpp, lib/Sema/CSWalker.cpp, lib/Sema/Constraint.cpp, lib/Sema/ConstraintSystem.cpp, test/GIL/GILPrinter.cpp, test/IRGen/IRGenTests.cpp, test/functional/run/overloads.glu
=> feat: add expressibleByXXLiteral for all literal builtin types

CMakeLists.txt, include/Basic/SourceLocation.hpp, include/Basic/SourceManager.hpp, include/Sema/ImportManager.hpp, include/Sema/Resolver.hpp, include/Sema/ScopeTable.hpp, include/Sema/Sema.hpp, lib/Basic/Diagnostic.cpp, lib/Basic/SourceManager.cpp, lib/Sema/CMakeLists.txt, lib/Sema/CSWalker.cpp, lib/Sema/GlobalScopeVisitor.cpp, lib/Sema/ImportManager.cpp, lib/Sema/ScopeTable.cpp, stdlib/CMakeLists.txt, stdlib/glucinfo.glu, stdlib/std.glu, test/GILGen/GILGenStmt.cpp, test/GILGen/GILGenTernary.cpp, test/functional/ASTPrinter/import.glu, test/functional/Sema/import_cyclic.glu, test/functional/Sema/import_self.glu, test/functional/run/import.glu, test/functional/run/import_systempaths.glu, tools/gluc/sources/main.cpp
=> [Sema] Feature: Imports

lib/Sema/CSWalker.cpp, lib/Sema/ImmutableAssignmentWalker.hpp, lib/Sema/UnreferencedVarDeclWalker.hpp, test/functional/Sema/immutable.glu, test/functional/Sema/unused_var.glu
=> Feature: Prevent Assignment to Immutable Variables

lib/ASTPrinter/ASTPrinter.cpp, lib/GIL/GILPrinter.cpp
=> Feature: Add colors to ASTPrinter

lib/Sema/ScopeTable.cpp
=> fix: cross module overloads

include/AST/Decl/Builtins.def, lib/IRGen/IRGen.cpp, lib/Parser/Parser.yy, lib/Sema/ConstraintSystem.cpp, lib/Sema/GlobalScopeVisitor.cpp, stdlib/CMakeLists.txt, stdlib/defaultImports/operators.glu, test/functional/run/operators.glu
=> Improve stdlib operators

include/Sema/ConstraintSystem.hpp, lib/Sema/CSWalker.cpp, lib/Sema/ConstraintSystem.cpp, lib/Sema/TypeVariableTyMapper.cpp, test/functional/run/nested-var.glu
=> fix: wrong compile error on nested variables in while/if bodies

lib/Sema/CSWalker.cpp, lib/Sema/SemanticPass/ValidMainChecker.hpp, test/functional/Sema/bad_main.glu
=> Feature: Check the validity of main

lib/GILGen/GILGenExpr.hpp, lib/GILGen/GILGenLValue.hpp, lib/Sema/CSWalker.cpp, test/functional/run/deref.glu
=> Feature: add deref op

tools/gluc/sources/CompilerDriver.cpp, tools/gluc/sources/CompilerDriver.hpp, tools/gluc/sources/main.cpp
=> Fix: `-O` option

include/Basic/MemoryArena.hpp, include/IRDec/TypeLifter.hpp, lib/IRDec/CMakeLists.txt, lib/IRDec/TypeLifter.cpp, test/CMakeLists.txt, test/IRDec/TypeLifter.cpp
=> feat(irdec): implement TypeLifter class for LLVM type lifting

lib/Sema/CSWalker.cpp, lib/Sema/SemanticPass/ValidTypeChecker.hpp, test/functional/Sema/bad_variable_type.glu
=> Feature: add a new checker in Sema to validate variable types

include/AST/Decl/EnumDecl.hpp, include/GIL/Instructions/Member.hpp, lib/GILGen/Context.hpp, lib/GILGen/GILGenExpr.cpp, lib/IRGen/IRGen.cpp, lib/Parser/Parser.yy, lib/Sema/GlobalScopeVisitor.cpp, test/functional/run/enum.glu
=> Feature: Reference enum fields
